CREATE DATABASE projeto;

USE projeto;

CREATE TABLE tb_user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE tb_tarefa (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL UNIQUE,
    is_completa BOOLEAN NOT NULL DEFAULT 0,
    criada_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user INT NOT NULL,
    FOREIGN KEY (user) REFERENCES tb_user(id)
);
